In [60]:
#KNN
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
import random


In [61]:
#Reading data from CSV file 
df=pd.read_csv('finalDataset.csv')
df.columns
np.random.seed(8)

In [62]:
#dividing data set into test train
df_featuers=['Centre Airbag-Driver', 'Vulnerable Road Users','Centre Airbag-Passenger', 'Tested Model','VIN From Which Rating Applies', 'Centre Airbag-Rear', 'Adult Occupant','Safety Assist', 'Year Of Publication', 'Class', 'Lane Assist System','Kerb Weight', 'AEB Vulnerable Road Users', 'Isofix/i-Size-Passenger', 'Child Occupant', 'Knee Airbag-Rear', 'Front Airbag-Rear']
x=df[df_featuers]
y=df['Rate']# here what we want to predecit
X_train , X_test, Y_train , Y_test= train_test_split(x,y,test_size=0.30,random_state=0)

In [63]:
kCls=KNeighborsClassifier(n_neighbors=5)
kCls.fit(X_train,Y_train)

KNeighborsClassifier()

In [64]:
kCls.get_params()

{'algorithm': 'auto',
 'leaf_size': 30,
 'metric': 'minkowski',
 'metric_params': None,
 'n_jobs': None,
 'n_neighbors': 5,
 'p': 2,
 'weights': 'uniform'}

In [65]:
y_pred= kCls.predict(X_test) 

In [66]:
accuracy_score(Y_test,y_pred)

0.6170212765957447

In [67]:
print(classification_report(Y_test,y_pred))
print(confusion_matrix(Y_test,y_pred))

              precision    recall  f1-score   support

         0.0       0.00      0.00      0.00         1
         1.0       0.00      0.00      0.00         1
         2.0       0.00      0.00      0.00         1
         3.0       0.14      0.17      0.15         6
         4.0       0.00      0.00      0.00        15
         5.0       0.76      0.81      0.79        70

    accuracy                           0.62        94
   macro avg       0.15      0.16      0.16        94
weighted avg       0.58      0.62      0.60        94

[[ 0  0  0  0  0  1]
 [ 0  0  0  0  0  1]
 [ 0  0  0  1  0  0]
 [ 0  0  0  1  1  4]
 [ 0  0  0  3  0 12]
 [ 0  0  0  2 11 57]]


c:\Users\rayoo\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\rayoo\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\rayoo\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [68]:
from sklearn.model_selection import cross_val_score
knn_cv = KNeighborsClassifier(n_neighbors=3)
cv_scores = cross_val_score(knn_cv, X_train, Y_train, cv=5)
#print each cv score (accuracy) and average them
print(cv_scores)
print('cv_scores mean:{}'.format(np.mean(cv_scores)))

c:\Users\rayoo\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:676: UserWarning: The least populated class in y has only 2 members, which is less than n_splits=5.
  warnings.warn(


[0.63636364 0.68181818 0.76744186 0.72093023 0.6744186 ]
cv_scores mean:0.6961945031712473
