In [12]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import tree
from sklearn.model_selection import train_test_split

from sklearn.metrics import classification_report
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import classification_report, confusion_matrix

## Spilt Dataset

In [16]:
# load dataset

df = pd.read_csv('finalDataset.csv')

df.index.name = 'index'
columns = df.columns
print(columns)

df.head()

Index(['Centre Airbag-Driver', 'Vulnerable Road Users',
       'Centre Airbag-Passenger', 'Tested Model',
       'VIN From Which Rating Applies', 'Centre Airbag-Rear', 'Adult Occupant',
       'Safety Assist', 'Year Of Publication', 'Class', 'Lane Assist System',
       'Kerb Weight', 'AEB Vulnerable Road Users', 'Isofix/i-Size-Passenger',
       'Child Occupant', 'Knee Airbag-Rear', 'Front Airbag-Rear', 'Rate'],
      dtype='object')


Centre Airbag-Driver  Vulnerable Road Users  Centre Airbag-Passenger  \
index                                                                         
0                       2.0                   81.0                      2.0   
1                       0.0                   68.0                      0.0   
2                       2.0                   70.0                      2.0   
3                       0.0                   74.0                      0.0   
4                       2.0                   71.0                      2.0   

       Tested Model  VIN From Which Rating Applies  Centre Airbag-Rear  \
index                                                                    
0              97.0                          139.0                   0   
1              29.0                          199.0                   0   
2              66.0                          125.0                   0   
3             221.0                          280.0                   0   
4              47.0                           14.0                   0   

       Adult Occupant  Safety Assist  Year Of Publication  Class  \
index                                                              
0                84.0           81.0               2022.0    4.0   
1                87.0           88.0               2022.0   10.0   
2                75.0           69.0               2022.0   12.0   
3                84.0           84.0               2022.0    6.0   
4                84.0           85.0               2022.0    4.0   

       Lane Assist System  Kerb Weight  AEB Vulnerable Road Users  \
index                                                               
0                     1.0       2532.0                        0.0   
1                     1.0       1423.0                        0.0   
2                     1.0       1334.0                        0.0   
3                     1.0       2434.0                        0.0   
4                     1.0       2123.0                        0.0   

       Isofix/i-Size-Passenger  Child Occupant  Knee Airbag-Rear  \
index                                                              
0                          1.0            89.0                 0   
1                          1.0            87.0                 0   
2                          1.0            84.0                 0   
3                          1.0            90.0                 0   
4                          0.0            89.0                 0   

       Front Airbag-Rear  Rate  
index                           
0                      0   5.0  
1                      0   5.0  
2                      0   4.0  
3                      0   5.0  
4                      0   5.0

In [20]:
X = df.iloc[:, : -2 ]
y = df.loc[: ,['Rate']]


# Split dataset to 80% for train and 20% for test
X_train, X_test, y_train, y_test = train_test_split(
    X, y, random_state=123, train_size = .8)


# train dataset
train = pd.concat([X_train,y_train], axis=1, ignore_index=False )
train.head()


# test dataset
test = pd.concat([X_test,y_test], axis=1, ignore_index=False )
test.head()




Centre Airbag-Driver  Vulnerable Road Users  Centre Airbag-Passenger  \
index                                                                         
172                     0.0              54.000000                      0.0   
11                      0.0              68.000000                      0.0   
20                      2.0              78.000000                      2.0   
303                     0.0              70.848624                      0.0   
72                      0.0              83.000000                      1.0   

       Tested Model  VIN From Which Rating Applies  Centre Airbag-Rear  \
index                                                                    
172            40.0                           97.0                   0   
11             29.0                          199.0                   0   
20            170.0                           46.0                   0   
303           214.0                            4.0                   0   
72            113.0                          197.0                   0   

       Adult Occupant  Safety Assist  Year Of Publication  Class  \
index                                                              
172              87.0           63.0               2019.0   10.0   
11               87.0           88.0               2022.0   10.0   
20               76.0           65.0               2022.0    8.0   
303              85.0           25.0               2016.0    6.0   
72               91.0           91.0               2022.0   10.0   

       Lane Assist System  Kerb Weight  AEB Vulnerable Road Users  \
index                                                               
172                   1.0       1199.0                        0.0   
11                    1.0       1423.0                        0.0   
20                    1.0       1397.0                        0.0   
303                   3.0       2050.0                        0.0   
72                    1.0       1810.0                        0.0   

       Isofix/i-Size-Passenger  Child Occupant  Knee Airbag-Rear  Rate  
index                                                                   
172                        0.0            86.0                 1   4.0  
11                         1.0            87.0                 0   5.0  
20                         1.0            84.0                 0   4.0  
303                        1.0            82.0                 1   3.0  
72                         1.0            87.0                 0   5.0

In [21]:
# save train and test as csv files 
train.to_csv('Train.csv')
test.to_csv('Test.csv')

## Build the Model

In [23]:
lr_list = [0.05, 0.075, 0.1, 0.25, 0.5, 0.75, 1] # learning rates

for learning_rate in lr_list:
    gb_clf = GradientBoostingClassifier(n_estimators=20, learning_rate=learning_rate, max_features=4, max_depth=2, random_state=0)
    gb_clf.fit(X_train, y_train.Rate)

    print("Learning rate: ", learning_rate)
    print("Accuracy score (training): {0:.3f}".format(gb_clf.score(X_train, y_train)))
    print("Accuracy score (validation): {0:.3f}".format(gb_clf.score(X_test, y_test)))
    
# Let's see what the performance was for different learning rates:


Learning rate:  0.05
Accuracy score (training): 0.911
Accuracy score (validation): 0.889
Learning rate:  0.075
Accuracy score (training): 0.948
Accuracy score (validation): 0.937
Learning rate:  0.1
Accuracy score (training): 0.956
Accuracy score (validation): 0.952
Learning rate:  0.25
Accuracy score (training): 0.992
Accuracy score (validation): 0.952
Learning rate:  0.5
Accuracy score (training): 1.000
Accuracy score (validation): 0.968
Learning rate:  0.75
Accuracy score (training): 1.000
Accuracy score (validation): 0.937
Learning rate:  1
Accuracy score (training): 1.000
Accuracy score (validation): 0.968


In [26]:
gb_clf2 = GradientBoostingClassifier(n_estimators=20, learning_rate=0.1, max_features=4, max_depth=2, random_state=0)
gb_clf2.fit(X_train, y_train.Rate)
predictions = gb_clf2.predict(X_test)

print("Confusion Matrix:")
print(confusion_matrix(y_test.Rate, predictions))

print("Classification Report")
print(classification_report(y_test.Rate, predictions))

Confusion Matrix:
[[ 0  1  0  0]
 [ 0  5  1  1]
 [ 0  0 10  0]
 [ 0  0  0 45]]
Classification Report
              precision    recall  f1-score   support

         2.0       0.00      0.00      0.00         1
         3.0       0.83      0.71      0.77         7
         4.0       0.91      1.00      0.95        10
         5.0       0.98      1.00      0.99        45

    accuracy                           0.95        63
   macro avg       0.68      0.68      0.68        63
weighted avg       0.94      0.95      0.94        63



/Users/maimonah_s/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/maimonah_s/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/maimonah_s/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
